- group:    Tutorial
  start:    01-02-2022 00:00
  deadline: 11-03-2022 23:59
  tasks:
    - task: add
      score: 0
- group:    Intro
  start:    01-02-2022 00:00
  deadline: 11-03-2022 23:59
  tasks:
    - task: combinations
      score: 100
    - task: conway
      score: 100
    - task: min-queue
      score: 100
- group:    Library Collections
  start:    12-02-2022 00:00
  deadline: 15-03-2022 23:59
  tasks:
    - task: comm
      score: 100
    - task: prefix
      score: 200
    - task: lru-cache
      score: 300
- group:    Traits
  start:    01-02-2022 00:00
  deadline: 31-03-2022 23:59
  tasks:
    - task: mpsc
      score: 200
