- group:    Tutorial
  start:    01-02-2022 00:00
  deadline: 22-02-2022 23:59
  tasks:
    - task: tutorial/add
      score: 0
- group:    Intro
  start:    01-02-2022 00:00
  deadline: 22-02-2022 23:59
  tasks:
    - task: intro/combinations
      score: 100
    - task: intro/conway
      score: 100
    - task: intro/min-queue
      score: 100
- group:    Library Collections
  start:    01-02-2022 00:00
  deadline: 15-03-2022 23:59
  tasks:
    - task: std-collections/comm
      score: 100
    - task: std-collections/prefix
      score: 200
    - task: std-collections/mpsc
      score: 200
    - task: std-collections/lru-cache
      score: 300
