toolchain: stable
allowed-patterns:
  - core/src/field.rs
  - core/src/generic.rs
  - core/src/hlist.rs
  - core/src/labelled.rs
  - core/src/transform.rs
  - derives/src/lib.rs
  - derives/src/generic.rs
  - derives/src/labelled.rs
  - src/lib.rs
steps:
  linters:
    - forbid-unsafe
    - cargo-fmt
    - cargo-clippy
  testing:
    - cargo-test
    - cargo-compile-test-mini-frunk
